apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cmatrix
  labels:
    app: my-cmatrix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-cmatrix
  template:
    metadata:
      labels:
        app: my-cmatrix
    spec:
      containers:
      - name: my-cmatrix
        image: vfilima/cmatrix
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"